networks:
  sb:
    driver: bridge

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
     - "2181:2181"
    networks:
      - sb
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    #restart: unless-stopped

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: kafka
    ports:
     - "9094:9094"
    networks:
      - sb
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "${KAFKA_TOPIC}:1:1,${KAFKA_SINK_TOPIC}:1:1"
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_LOG_RETENTION_BYTES: 4073741824
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_RETENTION_CHECK_INTERVAL_MS: 300000
    #restart: unless-stopped

  python-producer:
      build:
        context: ./producer
        dockerfile: Dockerfile
      container_name: producer
      env_file:
        - .env  # This file contains shared variables
      depends_on:
        - kafka
      networks:
        - sb
      #restart: unless-stopped

  flink-jobmanager:
    image: pyflink:latest
    container_name: flink-jobmanager
    env_file:
      - .env  # This file contains shared variables
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - ./flink_consumer/src:/opt/flink/usrlib/artifacts/python
      - ./data:/opt/flink/usrlib/data/
      - ./flink_consumer/myartifact/target:/opt/flink/usrlib/artifacts/java
    networks:
      - sb

  flink-taskmanager:
    image: pyflink:latest
    container_name: flink-taskmanager
    env_file:
      - .env  # This file contains shared variables
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.data.port:6121
        taskmanager.numberOfTaskSlots: 2
    depends_on:
      - flink-jobmanager
    command: taskmanager
    volumes:
      - ./data2:/opt/flink/usrlib/data/
    scale: 1
    networks:
      - sb

  consumer:
    image: consumer:latest
    container_name: consumer
    env_file:
      - .env  # This file contains shared variables
    depends_on:
      - kafka
    networks:
      - sb
    #restart: unless-stopped
